//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Windows.Documents.Reporting.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ReportingService {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReportingService() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Windows.Documents.Reporting.Resources.Localization.ReportingService", typeof(ReportingService).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The document could not be exported. ähnelt.
        /// </summary>
        internal static string DocumentCouldNotBeExportedExceptionMessage {
            get {
                return ResourceManager.GetString("DocumentCouldNotBeExportedExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The document could not be exported to PDF. ähnelt.
        /// </summary>
        internal static string DocumentCouldNotBeExportedToPdfExceptionMessage {
            get {
                return ResourceManager.GetString("DocumentCouldNotBeExportedToPdfExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The document could not be exported to XPS. ähnelt.
        /// </summary>
        internal static string DocumentCouldNotBeExportedToXpsExceptionMessage {
            get {
                return ResourceManager.GetString("DocumentCouldNotBeExportedToXpsExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The document could not be instantiated. ähnelt.
        /// </summary>
        internal static string DocumentCouldNotBeInstantiatedExceptionMessage {
            get {
                return ResourceManager.GetString("DocumentCouldNotBeInstantiatedExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The document could not be loaded from the XAML file, make sure, that the root element of the XAML file is of type Document. ähnelt.
        /// </summary>
        internal static string DocumentCouldNotBeLoadedExceptionMessage {
            get {
                return ResourceManager.GetString("DocumentCouldNotBeLoadedExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The document could not be rendered. ähnelt.
        /// </summary>
        internal static string DocumentCouldNotBeRenderedExceptionMessage {
            get {
                return ResourceManager.GetString("DocumentCouldNotBeRenderedExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The view model of the view could not be instantiated. ähnelt.
        /// </summary>
        internal static string ViewModelCouldNotBeInstantiatedExceptionMessage {
            get {
                return ResourceManager.GetString("ViewModelCouldNotBeInstantiatedExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The XAML file from which the document is to be loaded could not be found. ähnelt.
        /// </summary>
        internal static string XamlFileCouldNotBeFoundExceptionMessage {
            get {
                return ResourceManager.GetString("XamlFileCouldNotBeFoundExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The XAML file from which the document is to be loaded could not be loaded. ähnelt.
        /// </summary>
        internal static string XamlFileCouldNotBeLoadedExceptionMessage {
            get {
                return ResourceManager.GetString("XamlFileCouldNotBeLoadedExceptionMessage", resourceCulture);
            }
        }
    }
}
